kind: pipeline
type: docker
name: test
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - release
steps:
  - name: run tests
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
    - dotnet test
---
kind: pipeline
type: docker
name: build Deploy Images
depends_on:
  - test
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - release
steps:
  - name: build shared lib
    image: plugins/docker
    settings:
      dockerfile: Shared/Dockerfile
      context: Shared
      registry: registry.swerik.dev
      repo: registry.swerik.dev/poegamblinghelper/shared
      tags: latest
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    environment:
      DOCKER_BUILDKIT: 1

  - name: build backend
    image: plugins/docker
    settings:
      dockerfile: Backend/Dockerfile
      context: Backend
      registry: registry.swerik.dev
      repo: registry.swerik.dev/poegamblinghelper/backend
      tags: latest
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    environment:
      DOCKER_BUILDKIT: 1
    depends_on:
      - build shared lib

  - name: build frontend
    image: plugins/docker
    settings:
      dockerfile: Frontend/Dockerfile
      context: Frontend
      registry: registry.swerik.dev
      repo: registry.swerik.dev/poegamblinghelper/frontend
      tags: latest
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    environment:
      DOCKER_BUILDKIT: 1
    depends_on:
      - build shared lib

  - name: parallelism
    image: alpine
    commands:
      - echo finished
    depends_on:
      - build backend
      - build frontend
---
kind: pipeline
type: ssh
name: Deploy
depends_on:
  - build Deploy Images
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - release
server:
  host: erikpi
  user:
    from_secret: SSH_USERNAME
  password:
    from_secret: SSH_PASSWORD
steps:
  - name: docker login & Deploy
    commands:
      - docker --config /home/drone/.docker login localhost:5000 -u $USERNAME -p $PASSWORD
      - docker --config /home/drone/.docker compose up -d --pull always
    environment:
      USERNAME:
        from_secret: REGISTRY_USERNAME
      PASSWORD:
        from_secret: REGISTRY_PASSWORD
      POSTGRES_PASSWORD:
        from_secret: POSTGRES_PASSWORD