// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PoEGamblingHelper.Infrastructure.Database;

#nullable disable

namespace PoEGamblingHelper.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.Analytics.AnalyticsDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AnalyticsDay");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.Analytics.View", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("IpHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateOnly>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("View");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.Currency", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("League")
                        .HasColumnType("text");

                    b.Property<decimal>("ChaosEquivalent")
                        .HasColumnType("numeric");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "League");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.Gem.GemData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GemData");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.Gem.GemTradeData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("League")
                        .HasColumnType("text");

                    b.Property<decimal>("ChaosValue")
                        .HasColumnType("numeric");

                    b.Property<bool>("Corrupted")
                        .HasColumnType("boolean");

                    b.Property<string>("DetailsId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DivineValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExaltedValue")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("GemDataId")
                        .HasColumnType("uuid");

                    b.Property<int>("GemLevel")
                        .HasColumnType("integer");

                    b.Property<int>("GemQuality")
                        .HasColumnType("integer");

                    b.Property<int>("ListingCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "League");

                    b.HasIndex("GemDataId");

                    b.ToTable("GemTradeData");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("League");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.Stats.CurrencyResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("ChaosEquivalent")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CurrencyResult");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.Stats.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyResultId")
                        .HasColumnType("text");

                    b.Property<decimal>("CurrencyValue")
                        .HasColumnType("numeric");

                    b.Property<long>("GemTradeDataId")
                        .HasColumnType("bigint");

                    b.Property<string>("GemTradeDataLeague")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyResultId");

                    b.HasIndex("GemTradeDataId", "GemTradeDataLeague");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.TempleCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("League")
                        .HasColumnType("text");

                    b.PrimitiveCollection<decimal[]>("ChaosValue")
                        .IsRequired()
                        .HasColumnType("numeric[]");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "League");

                    b.ToTable("TempleCost");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.Gem.GemTradeData", b =>
                {
                    b.HasOne("PoEGamblingHelper.Domain.Entity.Gem.GemData", null)
                        .WithMany("Gems")
                        .HasForeignKey("GemDataId");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.Stats.Result", b =>
                {
                    b.HasOne("PoEGamblingHelper.Domain.Entity.Stats.CurrencyResult", "CurrencyResult")
                        .WithMany()
                        .HasForeignKey("CurrencyResultId");

                    b.HasOne("PoEGamblingHelper.Domain.Entity.Gem.GemTradeData", "GemTradeData")
                        .WithMany()
                        .HasForeignKey("GemTradeDataId", "GemTradeDataLeague")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyResult");

                    b.Navigation("GemTradeData");
                });

            modelBuilder.Entity("PoEGamblingHelper.Domain.Entity.Gem.GemData", b =>
                {
                    b.Navigation("Gems");
                });
#pragma warning restore 612, 618
        }
    }
}
